version: "3.7"
services:
  hearth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    env_file:
      - postgres.env

  postgres:
    image: postgres:9.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - postgres.env